[package]
name = "contract"
version = "1.0.0"

[dependencies]
eng-wasm = "0.1.3"
eng-wasm-derive = "0.1.3"
serde = "1.0.84"
serde_derive = "1.0.98"
rustc-hex = "2.0.1"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"